### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.cmd'

### ISSUE THREAD

**Issue by juancresc** [IPK-BIT/divbrowse#6]
When installing from pip using python3.9 on ubuntu
```

pip install divbrowse
Traceback (most recent call last):
  File "/root/divbrowse/venv/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/cli/spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 42, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 67, in <module>
    from . import _distutils
  File "/root/divbrowse/venv/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 20, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
(venv) ➜  divbrowse 

```

**Comment by juancresc** [comment]
sudo apt install python3.7-distutils
